# Generated by Django 4.1 on 2022-08-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('start_date', models.IntegerField()),
                ('final_date', models.IntegerField()),
            ],
        ),
    ]
