# Generated by Django 4.1 on 2022-08-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Show',
        ),
    ]
