# Generated by Django 4.1 on 2022-08-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0002_rename_cat_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='genre',
            field=models.ManyToManyField(to='show_app.genre'),
        ),
    ]
